---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-area-b
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: project for product-area-b resources
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-product-area-b
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
      revision: 'refactor'
      directories:
      - path: workloads/product-area-b/apps/*
      requeueAfterSeconds: 20
  template:
    metadata:
      name: 'workload-{{path.basename}}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: 'https://kubernetes.default.svc'
      project: product-area-a
      source:
        path: '{{ path }}'
        repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
        targetRevision: 'refactor'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
