namespace: argocd
resources:
- ../../base/

patches:
- patch: |-
    - op: replace
      path: /spec/source/path
      value: control-plane/overlays/dev
  target:
    kind: Application
    name: control-plane-root
