---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/jhollowayjc/argocd-gitops-playground'
        revision: 'refactor'
        directories:
        - path: 'apps/*'
  template:
    metadata:
      name: 'project-x-{{path.basename}}'
    spec:
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/jhollowayjc/argocd-gitops-playground'
        targetRevision: refactor
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
