---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app2
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-example
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'app2-{{name}}'
    spec:
      destination:
        namespace: app2-{{path.basename}}
        server: 'https://kubernetes.default.svc'
      source:
        path: '{{path}}'
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-example
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=background
          - CreateNamespace=true
