---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: control-plane-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
      revision: refactor
      directories:
      - path: add-ons
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
        targetRevision: refactor
        path: '{{path}}'
      destination:
        server: http://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
