---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: control-plane-product-area-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
      revision: refactor
      files:
      - path: product-areas/**/project.yaml
  template:
    metadata:
      name: 'product-area-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jhollowayjc/argocd-gitops-playground
        targetRevision: refactor
        path: control-plane/add-ons/argo-apps
        helm:
          valueFiles:
          - '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
