apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: argocd-lovely-plugin.yaml
  target:
    kind: Deployment
    name: argocd-repo-server

