apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.repoUrl }}
        revision: {{ .Values.targetRevision }}
        directories:
        - path: add-ons/env/{{ required "A valid environment is required!" .Values.environment }}/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        path: '{{`{{path}}`}}'
        repoURL: {{ .Values.repoUrl }}
        targetRevision: {{ .Values.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
        {{- if (.Values.disableAutoSync) }}
          prune: false
        {{- else }}
          prune: true
        {{- end }}
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m

