apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.repoUrl }}
        revision: {{ .Values.targetRevision }}
        files:
        - path: clusters/**/*.yaml
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        helm:
            valueFiles:
            - '{{`{{path}}`}}'
        path: 'applications/{{`{{path.filename}}`}}'
        repoURL: {{ .Values.repoUrl }}
        targetRevision: {{ .Values.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{namespace}}`}}'
      syncPolicy:
        automated:
        {{- if (.Values.disableAutoSync) }}
          prune: false
        {{- else }}
          prune: true
        {{- end }}
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
