---
apiVersion: v2
name: istio-system
description: A Helm chart for Argo Rollouts
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: base
  version: 1.16.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.16.3
  repository: https://istio-release.storage.googleapis.com/charts
